### ISSUE TITLE
Cannot export pdf files from zotero collection

### ISSUE THREAD

**Issue by cjpoor** [ZotPlus/zotero-better-bibtex#192]
Report ID: http://is.gd/lo2TJ5

I tried using Better BibTex to export a collection from zotero for Firefox. 

The export stalled for 6 hours.

The collection has 281 items, some of which are books, and most of which have pdf files attached. Most, if not all. attachments are in the zotero database attached to my Firefox profile.

System: Macbook Air 2014; OS X 10.10.3; Firefox 38.0.1; Zotero 4.0.26.4; Zotero Better Bib(La)Tex 0.9.31

***************************************** 

Other Add-ons and extensions: 

Ad-blocker for Gmail	2.8.3	true	jid0-AocRXUCRsLTCYvn6bgJERnwfuqw@jetpack
Adblock Plus	2.6.9	true	{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d}
Alpheios Basic Libraries	1.0beta2.4231.20130301	true	{4816253c-3208-49d8-9557-0745a5508299}
Alpheios Greek Tools	1.0beta2.4278.20140427	true	{0f1d7e06-6ce8-40b0-83f0-9783ee65ab9b}
Bookmark Duplicate Cleaner	0.2	true	bookmarkdup@localghost.net
bug506507(Preserve the order of bookmarks)	3.0	true	bug506507@alice
bug625778 (bookmarks contextmenu should work)	2.0	true	bug625778@alice0775
CACert Root Certificate	0.1	true	jid1-C86cNe1crgj9bw@jetpack
Change Bookmark Recent Folder List Length	1.1.0	true	change-bookmark-folder-list-length@makyen.foo
Compress Bookmarks Bar	0.1	true	compressbbar@simonwo.net
Download Manager (S3)	3.11	true	s3download@statusbar
DownThemAll!	2.0.18	true	{DDC359D1-844A-42a7-9AA1-88A850A938A8}
DuckDuckGo Plus	0.4.6	true	jid1-ZAdIEUB7XOzOJw@jetpack
EPUBReader	1.5.0.6	true	{5384767E-00D9-40E9-B72F-9CC39D655D6F}
Ghostery	5.4.5	true	firefox@ghostery.com
Google Scholar Button	1.1	true	button@scholar.google.com
LeechBlock	0.6.7.1	true	{a95d8332-e4b4-6e7f-98ac-20b733364387}
list.it	0.5.1.3	true	listit@csail.mit.edu
Local Filesystem Links	0.99.25	true	jid1-JAzC7z53jemo5Q@jetpack
LocalLink	0.5	true	{15756614-ffb8-498b-b961-bce537ea94fe}
LyZ	2.1.7.1-signed	true	lyz@zotero.org
NoScript	2.6.9.22	true	{73a6fe31-595d-460b-a920-fcc0f8843232}
PasswordMaker	1.7.8	true	{5872365e-67d1-4afd-9480-fd293bebd20d}
PatchForLibrary	7.1	true	{D9A7CBEC-DE1A-444f-A092-844461596C50}
Save-To-Read	0.4.2	true	save2read@konstantin.plotnikov
Saved From URL	1.4.20110629	true	{be102f2d-bf47-49db-8dcc-a2ccd1c8d376}
Saved Password Editor	2.9	true	savedpasswordeditor@daniel.dawson
Session Manager	0.8.1.6	true	{1280606b-2510-4fe0-97ef-9b5a22eafe30}
Terms of Service; Didn’t Read	0.4.1	true	jid0-3GUEt1r69sQNSrca5p8kx9Ezc3U@jetpack
TiddlyFox extension for Firefox	1.0alpha18	true	tiddlyfox@tiddlywiki.org
Total bookmarks	4.5.201405021257	true	totalbookmarks@cs0ip.net
TrackMeNot	0.8.16	true	trackmenot@mrl.nyu.edu
Video WithOut Flash	3.1.1	true	vwof@drev.com
Zotero Report Customizer	0.2.13	true	report-customizer@iris-advies.com
Zotero Word for Mac Integration	3.5.7	true	zoteroMacWordIntegration@zotero.org
ZoteroQuickLook	1.3.1	true	zoteroquicklook@gmail.com
ZotFile	4.1.5	true	zotfile@columbia.edu
zotxt	0.1.27	true	zotxt@e6h.org
Zutilo Utility for Zotero	1.2.10	true	zutilo@www.wesailatdawn.com

***************************************** 

I tired disabling these Add-ons:

Zotero Word for Mac integration
Zutilo
Zotero LibreOffice integration
Zotxt
Zotero Report customiser
ZotFile
Zotero Quicklook

I had already disabled Zotero to BibDesk auto-import and Automatic Zotero to BibTex exporter
and removed Zot2Bib and reversed the config pointer to automatically use his js file.

I attempted to export my collection with Better BibTex format export of files enabled

the .bib file was exported but not the files.

I then tried a test export on a single file (with pdf attachment) in a sub-collection called Theory.

Here is the Theory.bib exported file

@misc{Blunden,
  title = {Empirical {Social} {Psychology} and {Critical} {Theory}},
  url = {https://www.academia.edu/11716447/Empirical_Social_Psychology_and_Critical_Theory},
  abstract = {A critique of how Critical Theorists such as Habermas and Honneth have appropriated and failed to appropriate scientific theories of Psychology},
  timestamp = {2015-03-31 21:36:40},
  urldate = {2015-03-31},
  author = {Blunden, {Andy}},
  file = {Blunden_Empirical Social Psychology and Critical Theory.pdf:/Users/christopherpoor/Library/Application Support/Firefox/Profiles/zr7dj0jw.default/zotero/storage/4J69J4PA/Blunden_Empirical Social Psychology and Critical Theory.pdf:application/pdf;Snapshot:/Users/christopherpoor/Library/Application Support/Firefox/Profiles/zr7dj0jw.default/zotero/storage/MQ8ZFHXD/Empirical_Social_Psychology_and_Critical_Theory.html:text/html}
}

@comment{jabref-meta: groupsversion:3;}
@comment{jabref-meta: groupstree:
0 AllEntriesGroup:;
1 ExplicitGroup:Living systems\;0\;;
1 ExplicitGroup:Realism and knowledge\;0\;;
}

The BibLaTex url for this zotero sub-collection is

http://localhost:23119/better-bibtex/collection?/0/EUXPPB87.biblatex

Report ID: http://is.gd/lo2TJ5

The missing file is located on my Macbook Air at

/Users/christopherpoor/Library/Application Support/Firefox/Profiles/zr7dj0jw.default/zotero/storage/4J69J4PA/Blunden_Empirical_Social_Psychology_and_Critical_Theory.pdf

The pdf file is 268 KB with no security.

Better BibTex settings ——— :

I kept the default settings in Better BibTex preferences for “Citation”
The settings for “Import/Export” are:

[Y] Export to BibTex as ASCII

When a reference has both DOI and an URL, export [Y] both

Preserve capitalization  [Y] All words with capitals

[Y] Enable export by HTTP

_______

If you are able to help I would much appreciate it.

Many thanks,
Chris Poor
cjpoor@gmail.com

**Comment by retorquere** [comment]
I see no errors in the logfile. Could you do the following:

* Go into preferences->advanced, click "enable", then
* Export a single item with an attachment, then
* click "report zotplus error"

with the advanced logging enabled I will be able to see more. I just tried and I could export (on Yosemite) without problems.

**Comment by cjpoor** [comment]
Thanks so much for your very quick reply.
Trying to export collection with a single file but zotero hung up.
Will send any error report when possible.
Regards
Chris.

**Comment by retorquere** [comment]
I've published .33, which will allow you to send an error report from the BBT preferences even while the export is running. Make sure to open the preferences window before you start the export.

**Comment by cjpoor** [comment]
Thanks again.

Installed .33 and sent error report ID: http://is.gd/JrzrXb

It did take a few minutes to generate the report - at first I thought
Firefox had hung up.

Looks like a couple of my add-ons might be giving errors.

Your advice on how to resolve the problem will be greatly appreciated.

Regards,
Chris.

**Comment by retorquere** [comment]
.34 is out which fixes at least the bug that turned up in your logs. Could you see if that takes care of the problem, and if not, post a new log?

There are indeed other plugins that error out, but none of those should affect BBT.

**Comment by cjpoor** [comment]
So sorry. Still not working on my Mac. Error report coming. 


Sent from my T-Mobile 4G LTE Device

-------- Original message --------

**Comment by cjpoor** [comment]
Uh-oh. I'm still seeing the message "Please wait while the error report is submitted."


Sent from my T-Mobile 4G LTE Device

-------- Original message --------

**Comment by cjpoor** [comment]
Error report ID: http://is.gd/RSAdHH

**Comment by retorquere** [comment]
I have no idea who emits the "please wait" message, but certainly not BBT; the error log doesn't show any errors at all except one about message manager, which is extremely unlikely to be related.

Would it be possible for me to access your system via teamviewer? I am at a loss on how to reproduce this otherwise.

**Comment by cjpoor** [comment]
I can tell you that I got it to work on the test file - - for one little
while.

Just why, I don't really know - but I will tell you what I did:

-----------------
Rebooted Firefox and the Mac a couple of times.

Tried the export again - unchecking the "export collections" option - (this
turns itself on by default) and got a "files" folder but it seemed to be
the "snapshot" only (images, css etc) no pdf.

Deleted the "snapshot" attachment from the test zotero item (although this
didn't seem to take effect, in fact - why - ?)

Tried exporting with BBT again with the same "files" folder full of images,
css etc.

Exported with Better BibLaTeX. Got two "files" folders - One with the pdf
and one with the snapshot.

Exported with BibTex Tan-revised. Got the pdf only in "files"

Exported again with BBT. Got the two folders - one with the pdf.

Tried again with "Export Collections" on - got same two folders incl pdf.

Added an item to the collection.

Tried Better BibTex and Better BibLaTex exports with "Keep Updated" - no
files folders.

Retried without "Keep Updated" - no files folders.

Tried BibTex Tan-revised - got files folders with all files.


----------------

I think you may have inadvertently produced a form of artificial
intelligence which is capable of a kind of social learning.

But also - there may be a problem with the "keep updated" scripting.

And possibly there is some glitch in the way the pop-up calls the export
format scripts (ambiguous naming or something)?

BTW - should both "Better BibTex" and "Better BibLaTex" be listed in the
export options?

Should I remove one of these scripts?

Best regards,
Chris.

**Comment by retorquere** [comment]
> Tried the export again - unchecking the "export collections" option - (this turns itself on by default) and got a "files" folder but it seemed to be the "snapshot" only (images, css etc) no pdf.

Export collections just adds jabref-compatible collection information in the .bib file, it doesn't export files.

> Deleted the "snapshot" attachment from the test zotero item (although this didn't seem to take effect, in fact - why - ?)

You mean that you couldn't delete it? No idea what could be the cause of that.

> Tried exporting with BBT again with the same "files" folder full of images, css etc.

So that worked.

> Exported with Better BibLaTeX. Got two "files" folders - One with the pdf and one with the snapshot.

So that worked too

> Exported with BibTex Tan-revised. Got the pdf only in "files"

What is "BibTeX Tan-revised"?

> Exported again with BBT. Got the two folders - one with the pdf. Tried again with "Export Collections" on - got same two folders incl pdf.

That is to be expected. Turning "export collections" on or off will only result in a different .bib file (look at the end).

> Added an item to the collection. Tried Better BibTex and Better BibLaTex exports with "Keep Updated" - no files folders.

That is correct, but right now that's undocumented. If you choose "keep updated", it won't export files. This is needed to be able to cache the generated bibtex for fast regeneration -- background export would be unworkable without it. On the upside, cached export is *fast* -- easily 20x faster than non-cached. If you export files, the cache is bypassed.

> Retried without "Keep Updated" - no files folders. This is where it gets interesting. So if you have picked "Keep updated" once, then export with "export files" ticked, you get no files?

> Tried BibTex Tan-revised - got files folders with all files.

Wait, is this the exporter from http://www.rtwilson.com/academic/autozotbib ? No problem, but then at least I know what we're talking about.

> I think you may have inadvertently produced a form of artificial intelligence which is capable of a kind of social learning.

More likely a bug where some settings are retained, or an overly enthusiastic cache interfering.

> But also - there may be a problem with the "keep updated" scripting. And possibly there is some glitch in the way the pop-up calls the export format scripts (ambiguous naming or something)?

I don't understand this?

> BTW - should both "Better BibTex" and "Better BibLaTex" be listed in the export options?

Yes -- BibTeX and BibLaTeX are subtly incompatible.

> Should I remove one of these scripts?

Which scripts?

**Comment by cjpoor** [comment]
On Sat, May 23, 2015 at 1:35 AM, retorquere <notifications@github.com>
wrote:

> Tried the export again - unchecking the "export collections" option -
> (this turns itself on by default) and got a "files" folder but it seemed to
> be the "snapshot" only (images, css etc) no pdf.
>
> Export collections just adds jabref-compatible collection information in
> the .bib file, it doesn't export files.
>
> Deleted the "snapshot" attachment from the test zotero item (although this
> didn't seem to take effect, in fact - why - ?)
>
> You mean that you couldn't delete it? No idea what could be the cause of
> that.
>
I assume this is because the "item" in the collection is a pointer to the
zotero library. I try to make my collections only by dragging "copies"
(which I believe are more like aliases) from the zotero library (its
"master collection" if you like).

>  Tried exporting with BBT again with the same "files" folder full of
> images, css etc.
>
> So that worked.
>
No - the "snapshot" was exported but not the pdf.

>  Exported with Better BibLaTeX. Got two "files" folders - One with the
> pdf and one with the snapshot.
>
> So that worked too
>
> Exported with BibTex Tan-revised. Got the pdf only in "files"
>
> What is "BibTeX Tan-revised"?
>
> Exported again with BBT. Got the two folders - one with the pdf. Tried
> again with "Export Collections" on - got same two folders incl pdf.
>
> That is to be expected. Turning "export collections" on or off will only
> result in a different .bib file (look at the end).
>
> Added an item to the collection. Tried Better BibTex and Better BibLaTex
> exports with "Keep Updated" - no files folders.
>
> That is correct, but right now that's undocumented. If you choose "keep
> updated", it won't export files. This is needed to be able to cache the
> generated bibtex for fast regeneration -- background export would be
> unworkable without it. On the upside, cached export is *fast* -- easily
> 20x faster than non-cached. If you export files, the cache is bypassed.
>
OH. I didn't realize that. Where is the documentation? I did see that you
referred to the docs being written by yourself, but when I looked for them
I couldn't find them.

>  Retried without "Keep Updated" - no files folders. This is where it gets
> interesting. So if you have picked "Keep updated" once, then export with
> "export files" ticked, you get no files?
>
> Tried BibTex Tan-revised - got files folders with all files.
>
> Wait, is this the exporter from
> http://www.rtwilson.com/academic/autozotbib ? No problem, but then at
> least I know what we're talking about.
>
Yes  - that's the one.

>  I think you may have inadvertently produced a form of artificial
> intelligence which is capable of a kind of social learning.
>
> More likely , or an overly enthusiastic cache interfering.
>
That "settings retained" idea seems likely.

>  But also - there may be a problem with the "keep updated" scripting. And
> possibly there is some glitch in the way the pop-up calls the export format
> scripts (ambiguous naming or something)?
>
> I don't understand this?
>
I'm assuming all this is done with javascript - no? So what I was referring
to is pretty much what you surmised: "a bug where some settings are
retained" - and my "glitch" is perhaps the "subtly incompatible" point you
make below?

>  BTW - should both "Better BibTex" and "Better BibLaTex" be listed in the
> export options?
>
> Yes -- BibTeX and BibLaTeX are subtly incompatible.
>
> Should I remove one of these scripts?
>
> Which scripts?
>
I got this notion from Robin Wilson's instructions:

To install the new BibTeX export translator you need to copy it to the
Zotero translators directory. To find this directory, open Zotero
Preferences, choose the Advanced tab and click *Show Data Directory*.
Inside this directory, open the translators directory and paste in the
BibTeX_RobinTan.js file. This exporter will now be available when manually
exporting from Zotero.

I'm assuming the .js file is a javascript - and that your BBT is one too.
And please - I am still confused - Is your BBT "Better BibTex" or "Better
BibLaTeX"?

In my "translators" folder there are several .js files that were modified a
couple of minutes before I was doing these test exports I described
(perhaps by the reboot of the Mac). These files include BibTeX AUX
Scanner.js; LaTeX Citation.js; Pandoc Citation.js; Zotero TestCase.js;
Better BibLaTeX.js; Better BibTeX.js; ACM Digital Library.js; and BibTeX.js

BibTeX_RobinTan.js was not modified last night. Perhaps that is why it
still functions as expected.

Regards,
Chris.

**Comment by retorquere** [comment]
>>> Deleted the "snapshot" attachment from the test zotero item (although this didn't seem to take effect, in fact - why - ?)
>>
>> You mean that you couldn't delete it? No idea what could be the cause of that.
>
> I assume this is because the "item" in the collection is a pointer to the zotero library. I try to make my collections only by dragging "copies" (which I believe are more like aliases) from the zotero library (its
"master collection" if you like).

Oh, that. That could be, but that's unrelated to BBT.

> No - the "snapshot" was exported but not the pdf.

OK, so that's a bug. I just can't reproduce it right now. I can build an instrumented version with extra logging to see what's going on.

>> That is correct, but right now that's undocumented. If you choose "keep
>> updated", it won't export files. This is needed to be able to cache the
>> generated bibtex for fast regeneration -- background export would be
>> unworkable without it. On the upside, cached export is *fast* -- easily
>> 20x faster than non-cached. If you export files, the cache is bypassed.
>
> OH. I didn't realize that. Where is the documentation? I did see that you
> referred to the docs being written by yourself, but when I looked for them
> I couldn't find them.

It's not documented right now. That still needs to be done.

>  Retried without "Keep Updated" - no files folders. This is where it gets
> interesting. So if you have picked "Keep updated" once, then export with
> "export files" ticked, you get no files?

This would be very helpful to get confirmation on.

>> More likely , or an overly enthusiastic cache interfering.
>
> That "settings retained" idea seems likely.

Settings retained?

>  But also - there may be a problem with the "keep updated" scripting. And
> possibly there is some glitch in the way the pop-up calls the export format
> scripts (ambiguous naming or something)?

Nope, that's standardized.

>> Yes -- BibTeX and BibLaTeX are subtly incompatible.
>
> Should I remove one of these scripts?

No. The BibTeX and the LaTeX *formats* are different, and are intended for different bibliography processors -- BibTeX is for bibtex, BibLaTeX is for biber. The BBT plugin installs 6 translators to be exact.

> I got this notion from Robin Wilson's instructions:

Ah, that. No, BBT takes care of installation and deinstall of its translators. No need to do anything by hand.

> And please - I am still confused - Is your BBT "Better BibTex" or "Better BibLaTeX"?

Both (and more)

> In my "translators" folder there are several .js files that were modified a couple of minutes before I was doing these test exports I described (perhaps by the reboot of the Mac). These files include BibTeX AUX Scanner.js; LaTeX Citation.js; Pandoc Citation.js; Zotero TestCase.js; Better BibLaTeX.js; Better BibTeX.js; ACM Digital Library.js; and BibTeX.js

Most of these are installed by BBT. Only the ACM translator and the BibTeX.js aren't; they must have updated because Zotero published a new version.

> BibTeX_RobinTan.js was not modified last night. Perhaps that is why it still functions as expected.

The modification date really doesn't mean much; the BBT translators will always be updated at startup of Zotero.

I'll need to either build an instrumented version of BBT to see what's going on, or log in using TeamViewer. I haven't been able to reproduce the problem yet here.

**Comment by cjpoor** [comment]
Cleared cache with ccleaner.

BBT .35 update 23 May 2015 10.30 am

BBT and BB(L)T exported files OK.

BB(L)T hangs up FF when exporting with “keep updated”

Restarted FF. Export with BBT + “keep updated” gives no files and txt file
(no extension) rather than .bib file - this is what it says:

——————————

@misc{Blunden,
  title = {Empirical {Social} {Psychology} and {Critical} {Theory}},
  url = {
https://www.academia.edu/11716447/Empirical_Social_Psychology_and_Critical_Theory
},
  abstract = {A critique of how Critical Theorists such as Habermas and
Honneth have appropriated and failed to appropriate scientific theories of
Psychology},
  timestamp = {2015-03-31 21:36:40},
  urldate = {2015-03-31},
  author = {Blunden, {Andy}},
  file = {Blunden_Empirical Social Psychology and Critical
Theory.pdf:/Users/christopherpoor/Library/Application
Support/Firefox/Profiles/zr7dj0jw.default/zotero/storage/4J69J4PA/Blunden_Empirical_Social_Psychology_and_Critical_Theory.pdf:application/pdf;Snapshot:/Users/christopherpoor/Library/Application
Support/Firefox/Profiles/zr7dj0jw.default/zotero/storage/MQ8ZFHXD/Empirical_Social_Psychology_and_Critical_Theory.html:text/html}
}

@article{Drew2014,
  title = {The {Agency} of {Children}: {From} {Family} to {Global} {Human}
{Rights} by {A}1  -  {David} {Oswell} , {PB}  - {Cambridge} {University}
{Press} , {Cambridge}, 2013, {\textsterling}16.99, 305pp},
  volume = {62},
  copyright = {{\textcopyright} 2014 {The} {Authors}. {The} {Sociological}
{Review} {\textcopyright} 2014 {The} {Editorial} {Board} of {The}
{Sociological} {Review}},
  issn = {1467-954X},
  shorttitle = {The {Agency} of {Children}},
  url = {http://onlinelibrary.wiley.com/doi/10.1111/1467-954X.12146/abstract
},
  doi = {10.1111/1467-954X.12146},
  language = {en},
  timestamp = {2014-09-25 01:27:43},
  number = {1},
  urldate = {2014-09-25},
  journal = {The {Sociological} {Review}},
  author = {Drew, {Isobel}},
  month = feb,
  year = {2014},
  keywords = {agency,childhood,Democratization.,family,household,human
rights,intimacy,Power},
  pages = {222--224},
  file = {Full Text PDF:/Users/christopherpoor/Library/Application
Support/Firefox/Profiles/zr7dj0jw.default/zotero/storage/4ZD5G2QM/Drew -
2014 - The Agency of Children From Family to Global
Huma.pdf:application/pdf;Snapshot:/Users/christopherpoor/Library/Application
Support/Firefox/Profiles/zr7dj0jw.default/zotero/storage/MVEC2BNE/abstract.html:text/html}
}

@comment{jabref-meta: groupsversion:3;}
@comment{jabref-meta: groupstree:
0 AllEntriesGroup:;
1 ExplicitGroup:Living systems\;0\;;
1 ExplicitGroup:Realism and knowledge\;0\;;
}

——————————

Error report ID: http://is.gd/UWiZxY

———
Exported once more with BBT without "keep updated"
.bib file exported OK but no files.



Why don’t I set up an account for you to ssh onto my Mac?

Chris.

**Comment by retorquere** [comment]
ssh won't do me much good since I won't be able to drive firefox. Teamviewer will (or chrome remote desktop for that matter), and you'll be sure that there won't be lingering access left. If you want, I can create a version that does extended logging, and I won't need any remote access, but you'll have to install those and capture the logs.

The error log posted has no errors, so I can't yet tell what's causing FF to stall out.

Let me see if I summarize the last report correctly:

1. BB(L)T export with "Export Files": OK
2. BB(L)T export with "Keep updated": FF Stalls.
3. After restart, export with "Keep updated", sort of OK, but filename is wrong (no extension) and no files exported (which is the expected behavior, sorry -- keep updated will always imply no file export, and the checkbox will be ignored)

In principle it should be possible to gain some insight into 2 without instrumented builds, using https://developer.mozilla.org/en-US/docs/Mozilla/Performance/Profiling_with_the_Built-in_Profiler. The output of that would help me to instrument a debug build more effectively.

**Comment by cjpoor** [comment]
OK. Installed Gecko profiler.
What do you need for (you personally) to have Teamviewer access?

**Comment by cjpoor** [comment]
Hi there,
Ready with Teamviewer installed.
I assume I will not need to post my ID and password to the issues on Github.
Is there a private email address I can send these to?
Chris.

**Comment by retorquere** [comment]
Right, do not post them here! My email address is emiliano.heyns@iris-advies.com, let's first schedule a time, and then exchange credentials. It will also be very helpful if you have a second device (other PC, smartphone, whatnot) so we can have a chat channel open while I'm controlling your screen; if you give me your email, I'll invite you to a private slack channel. My time this weekend will be limited unfortunately -- family obligations.

**Comment by retorquere** [comment]
Could you start with the version at http://is.gd/tbHGO0 if https://circleci.com/gh/ZotPlus/zotero-better-bibtex/571 is green? After install & restart, go into Preferences->Advanced, enable ZotPlus debug logging, restart FF again, do an export, and send me the new logs. I wish I could do teamviewer right now, but this is all I can do while sneaking out on the family activities every now and then :(

**Comment by cjpoor** [comment]
Hi Emiliano,

Back at my Mac. Looking at circleci the status is Failed at present (red).
So I guess I'm waiting for .36 - right?

BTW I am available on Telegram, viber, Whatsapp and
Skype: participant538

Hope you are having a good weekend,
Chris.

**Comment by retorquere** [comment]
Circle has been having issues. The same build is now green. You can try the
build from the share.

**Comment by cjpoor** [comment]
On Sun, May 24, 2015 at 5:15 AM, retorquere <notifications@github.com>
wrote:

> Could you start with the version at http://is.gd/tbHGO0 if
> https://circleci.com/gh/ZotPlus/zotero-better-bibtex/571 is green? After
> install & restart, go into Preferences->Advanced, enable ZotPlus debug
> logging, restart FF again, do an export, and send me the new logs. I wish I
> could do teamviewer right now,
>


Hi,
I reinstalled .35

When you say
enable ZotPlus debug logging

I'm assuming you mean zotero advanced preferences.

However, restarting FF resets the "enable" status so I just clicked
"enable" again.

I did an export with "Export Files" "Export Notes" and "Export Collections"
ticked.

Good result: .bib and .pdf exported.

Error report ID: http://is.gd/8bbjjJ

Did another export with "Keep Updated" also ticked.

Got only a text file with no .bib extension.

Error report ID: http://is.gd/aLXbrZ

Cheers,
Chris.

**Comment by retorquere** [comment]
The version you found on the Google drive folder adds a checkbox at the
bottom of the advanced preferences screen for ZotPlus debugging. Checking
that will keep logging on after restarts, to make sure

**Comment by cjpoor** [comment]
Oh. Sorry, I didn't see that.
I will try later tonight.
Thanks.

**Comment by retorquere** [comment]
I have put out .36 which (a.o.) includes the optional debugging; no need to use the one from the GDrive folder right now.

**Comment by cjpoor** [comment]
Updated BBT. Restarted FF.
Set ZotPlus extended debug logging.
Attempted export.
Sorry to say - Zotero hung up.
No export of anything.

Error report ID: http://is.gd/hNbSWa

Regards,
Chris.

**Comment by retorquere** [comment]
Did you restart after enabling extended debugging?

**Comment by cjpoor** [comment]
Sorry - I can’t remember.
Trying again:

Set ZotPlus extended and and zotero debug logging to enable after restart.
Restarted FF.
Attempted export with only “Export Notes” and “Export Files” checked.
Zotero hung up again.
No export of anything.
But Finder shows an arrow head (as if there is something in the folder).
In terminal “pwd” and “ls” show nothing in the directory I exported to.

Error report ID: http://is.gd/onLiDb

Regards,
Chris.

**Comment by retorquere** [comment]
I'm afraid the export will have to run in full before anything interesting is captured. Could you let BBT upgrade itself to 0.10.2 and try again? The extended logging will still be on unless you've turned it off, so you can just start directly after the update.

**Comment by cjpoor** [comment]
Hi Emiliano,

Zotplus report - 27 May 2015

Updated Zotplus through FF Add-ons page.

1st Export was good with “Export Notes” and “Export Files” ticked (included
.bib and .pdf)
2nd Export after adding a new item to the collection and with “Keep
Updated” (now prevents ticking of “Export Files”) ticked did not make a new
.bib file.
Also: There was nothing in the Automatic Export fields of BibTex
preferences.

Error report ID: http://is.gd/3oL09U

3rd Export attempt repeat of 2nd (with “Keep Updated” ticked).
Created new .bib file.
(The only odd thing here is that, instead of overwriting the old .bib file,
the old files are placed in a new folder below the new .bib file.)

Added new item to collection.
.bib file was updated!

So it now seems to work as expected. Congratulations!
(Although I noticed that there is still nothing in the “Automatic Export”
fields of BBT preferences - perhaps that will appear after restarting FF?)

Just in case it’s of use to you, I sent another “Error report”
ID: http://is.gd/nJBvSU

I will let you know if I get any more errors.

Now I just need to figure out a convenient way of keeping my attached .pdfs
updated.

Thank you for all the work you put into this feature!
Best regards,
Chris.

**Comment by retorquere** [comment]
> 1st Export was good with “Export Notes” and “Export Files” ticked (included .bib and .pdf)
>
> 2nd Export after adding a new item to the collection and with “Keep Updated” (now prevents ticking of “Export Files”) ticked did not make a new .bib file.

The first is what I expected (keep updated doesn't do file exports), but if I understand you correctly, ticking "keep updated" and doing an export does nothing?

> Also: There was nothing in the Automatic Export fields of BibTex preferences.

So it didn't register the auto-export. There was something strange going on where sometimes the `.bib` file extension was not passed by Zotero; it might explain why no file showed up, certainly on a Mac (why do people insist on hiding file extensions?!)

> 3rd Export attempt repeat of 2nd (with “Keep Updated” ticked). Created new .bib file. (The only odd thing here is that, instead of overwriting the old .bib file, the old files are placed in a new folder below the new .bib file.)

Might be related to the missing file extension. The version at https://drive.google.com/drive/folders/0B8tW4NMPfEosfkFETUV0V2l0N3NHZHEyQk5SUm03TjZmS1RoVmlBTmdHclUtcTRzZ2VHclU has the extension patch -- could you try?

> Added new item to collection..bib file was updated! So it now seems to work as expected. Congratulations! (Although I noticed that there is still nothing in the “Automatic Export” fields of BBT preferences - perhaps that will appear after restarting FF?)

No, that should only require a close and re-open of the preferences window. If you close and open while debug is enabled, any errors will show up in the log, and I could investigate.

> I will let you know if I get any more errors.

Does FF still hang up?

> Now I just need to figure out a convenient way of keeping my attached .pdfs updated.

The problem is that I cache the exported BibTeX code per item per export config settings (so things like "export notes"). For all settings in the export window, I can re-use the cached BibTeX even if you export the item as part of many collections. Problem is that the resulting BibTeX code will change per target directory when exporting files, as it has relative paths, not absolute paths, so I won't be able to re-use cache entries. I could of course just cache a separate entry for each variant for each target directory, but not only will this enlarge the memory consumption, it will also make export slower generally, as there's a bigger cache to search through for hits, and I'd have to do file compares (slow) to see whether an attachment would need exporting. If I ever find a way to do links (symbolic or hard) in a cross-platform fashion, perhaps it could still be done.

> Thank you for all the work you put into this feature!

Thanks you for your patience and your feedback. It is hugely appreciated.

**Comment by retorquere** [comment]
0.10.6 has the patch -- forget about the version I mentioned earlier. Could you see whether 0.10.6 fixes the missing extension problem? And could you for all remaining problems please describe succinctly:

1. what you did
2. what you expected
3. what you got

I must admit I've gotten a little lost in this longer thread, and I no longer remember which problems are still live.

**Comment by cjpoor** [comment]
Reply to Emiliano 28 May 2015

Copied from his previous reply:

1st Export was good with “Export Notes” and “Export Files” ticked (included
.bib and .pdf)
2nd Export after adding a new item to the collection and with “Keep
Updated” (now prevents ticking of “Export Files”) ticked did not make a new
.bib file.
The first is what I expected (keep updated doesn't do file exports), but if
I understand you correctly, ticking "keep updated" and doing an export does
nothing?
        That is what happened at first
Also: There was nothing in the Automatic Export fields of BibTex
preferences.
So it didn't register the auto-export. There was something strange going on
where sometimes the .bib file extension was not passed by Zotero; it might
explain why no file showed up, certainly on a Mac (why do people insist on
hiding file extensions?!)
        This just seems to be a matter of re-opening the preferences
window, so hardly a problem
3rd Export attempt repeat of 2nd (with “Keep Updated” ticked). Created new
.bib file. (The only odd thing here is that, instead of overwriting the old
.bib file, the old files are placed in a new folder below the new .bib
file.)
Might be related to the missing file extension. The version at
https://drive.google.com/drive/folders/0B8tW4NMPfEosfkFETUV0V2l0N3NHZHEyQk5SUm03TjZmS1RoVmlBTmdHclUtcTRzZ2VHclU
has the extension patch -- could you try?
        This was all done after updating to 0.10.6. The missing file
extension did not occur during this session
Added new item to collection..bib file was updated! So it now seems to work
as expected. Congratulations! (Although I noticed that there is still
nothing in the “Automatic Export” fields of BBT preferences - perhaps that
will appear after restarting FF?)
No, that should only require a close and re-open of the preferences window.
If you close and open while debug is enabled, any errors will show up in
the log, and I could investigate.
        Right
I will let you know if I get any more errors.
Does FF still hang up?
        Nope - only the error reporting takes a long time
Now I just need to figure out a convenient way of keeping my attached .pdfs
updated.
The problem is that I cache the exported BibTeX code per item per export
config settings (so things like "export notes"). For all settings in the
export window, I can re-use the cached BibTeX even if you export the item
as part of many collections. Problem is that the resulting BibTeX code will
change per target directory when exporting files, as it has relative paths,
not absolute paths, so I won't be able to re-use cache entries. I could of
course just cache a separate entry for each variant for each target
directory, but not only will this enlarge the memory consumption, it will
also make export slower generally, as there's a bigger cache to search
through for hits, and I'd have to do file compares (slow) to see whether an
attachment would need exporting. If I ever find a way to do links (symbolic
or hard) in a cross-platform fashion, perhaps it could still be done.
        I think I vaguely understand what the problem is here. The only
possibly relevant mechanism that I am somewhat familiar with (not knowing
code - as yet) is file comparison as done by
https://sourcegear.com/diffmerge/ for example. It makes sense to me at
present to have a manual routine for updating the pdfs (I use them in
Docear).

Thanks again for all your good work!
Chris.
P.S. updated to 0.10.22 but have not tested it yet.

**Comment by retorquere** [comment]
Please don't copy from the previous reply; you're responding by mail, which is OK, but I look at the issue tracker, and github's mail import makes a right mess of things (see https://github.com/ZotPlus/zotero-better-bibtex/issues/192). I appreciate that this is an effort you shouldn't have to make, but the resulting big wall of text makes it nigh impossible to discern what's been fixed and what's still broken. If you could go to https://github.com/ZotPlus/zotero-better-bibtex/issues/192 and just fill out those 3 questions in the bug tracker itself it would be hugely appreciated.

**Comment by retorquere** [comment]
BTW Docear should be able to find the attachments as the exported file will have absolute paths into the Zotero storage directory. "Export File Data" just means "copy file data".

**Comment by cjpoor** [comment]
So sorry. I see what you mean. Here it is in a, hopefully, more GitHub friendly format:

(A) 
1. I updated to 0.10.6 .
In the export dialog I ticked “Export Notes” and “Export Files” only.
2. I expected the test Zotero collection to be exported to BibTex format as one .bib file and one .pdf file.
3. I got the test Zotero collection exported to BibTex format as one .bib file and one .pdf file (into my test folder).

(B)  
1. I added an item to the Zotero test collection and ticked “Keep updated” in the BBT export dialog and did another export.
2. I expected to see the  Auto-Export fields in BBT preferences auto-populated and 
I also expected to see the previously exported .bib file (in the folder I exported to) changed to reflect the new item in the Zotero collection that I exported from.
3. At first there was nothing in the Auto-Export fields. However, after later re-opening the BBT preferences window, the fields were populated.
However, on this first attempt the (previously) exported .bib file in the exported folder did not change.
Error report ID: http://is.gd/3oL09U

(C)
1. I tried adding another item to the Zotero test collection and, with “Keep Updated” ticked in the BBT export dialog, did another export.
2. I expected the previously exported .bib file (in the folder I exported to) to be changed to reflect the new item in the Zotero collection that I exported from. 
I also expected to see the this updated export .bib file overwrite the original exported .bib file (in the same folder).
3. The exported .bib file was updated and now reflected the new items in the Zotero test collection.
However, this export process created a new folder (named after the Zotero test collection that was exported) and filed the original exported .bib file and “files" (pdf) folder in this new folder (at a lower level). The updated .bib file is now in the top level of the folder I created as the test export folder.
Error report ID: http://is.gd/nJBvSU

**Comment by cjpoor** [comment]
I'm afraid I also lost track of this thread somewhat. 
What I just sent is the same as sent previously - under the heading "Zotplus report - 27 May 2015" - but the new post is a better organized telling of the story.
"The wall of text" that I sent in the email was my attempt to respond to your comments in you reply to me.
The only things to add are that - 
These latest exports (now reported here for a second time) were all done after updating through FF to 0.10.6 - and -
The missing file extension problem did not occur during this session - that is: all exports of the .bib file had the .bib extension.
I will check out Docear gets on finding the attachments and also try a regular export of a full collection when I have time.
Regards,
Chris.

**Comment by retorquere** [comment]
Please don't apologise -- github encourages reply-by-mail for good reason: the less friction there is in submitting error reports, the better. They're just not doing a very good job of keeping it readable.

You can let BBT update to 0.10.24 BTW.

So, to recap (and thanks for the breakdown BTW -- again: much appreciated):

(A) passes.

(B) has a known problem that auto-updates don't show until you re-open the preferences. I haven't yet found a way to fix this. Otherwise, you seem to still have the problem with missing extensions and spurious directories being created; your log files show this is the case, but in a later message you indicate this could be fixed (which is what I had expected)? The extension missing could explain why the .bib file didn't update. Can you please re-test on 0.10.24? I've added more debug logging.

(C) seems to suffer from the same problems as (B). I first need to find out why the extension is missing -- all the rest is likely collateral damage from that.

**Comment by cjpoor** [comment]
OK. Will update and retest. BTW I have Teamviewer waiting if you want to use it.

**Comment by cjpoor** [comment]
OK. Will update and retest. BTW I have Teamviewer waiting if you want to use it.

8.55 pm 28 May 2015

Updated to BBT 0.10.24
Checked Zotero and BBT error reporting preferences set.
Restarted FF.

(D) 
1. Tried export of new Zotero test collection with only “Export Notes” and “Export Files” ticked.
2. I expected the test Zotero collection to be exported to BibTex format as one .bib file and one HTML text file.

3. I got what I expected. But note: 
this export process created a new folder (named after the Zotero test collection that was exported) at a lower level. The .bib file is now in this second level of the folder I created as the test export folder. The HTML text file is in a folder with a Zotero-like number for its name at the next level down 
(E) 
1. Added a Zotero citation with attached .pdf file to the test Zotero collection (by drag and drop)
Exported the Zotero test collection to the same test folder as in (D) with “Keep Updated” ticked.
2. I expected the previously exported .bib file (in the folder I exported to) to be changed to reflect the new item in the Zotero collection that I exported from. 
I also expected to see the this updated export .bib file overwrite the original exported .bib file in the same position.
I did not expect the pdf. file to be exported since this option is turned of by ticking “Keep Updated”
3. The exported .bib file was updated  and now reflected the new item in the Zotero test collection.
However, this export process did not create a new folder (named after the Zotero test collection that was exported) and file the original exported .bib file and “files” folder in this new folder (at a lower level). The updated .bib file is now in the top level of the folder I created as the test export folder, the first exported .bib file is in the lower level folder auto created in (D) and the HTML text file is another two levels down i.e:
~/Desktop/28.1 - 9.12pm/Capitalism versus Democracy via the secret state/files/5214/The New Politics of the Welfare State.html
Error Report ID: http://is.gd/PREZ7N

**Comment by retorquere** [comment]
Do you have time for a teamviewer session right now? Don't post passwords here BTW.

**Comment by cjpoor** [comment]
Sure.

**Comment by retorquere** [comment]
Can you do hangouts?

**Comment by cjpoor** [comment]
Yes. I have Hangouts. You just use my email address, right?

**Comment by retorquere** [comment]
I've found you (using cjpoor@gmail.com), but it says you're offline

**Comment by retorquere** [comment]
I think I've got it. I need to do a little more testing, but I think that last checkin did it.

**Comment by retorquere** [comment]
OK, things are looking good. Could you try the version at https://zotplus.github.io/better-bibtex/#debug ?

**Comment by retorquere** [comment]
I've done some more tests, and things are looking good, and a the code looks just a bit better to boot. Sorry it took me so long to track this one down, and thanks for sticking it out. If 0.10.25 doesn't fix all of the above problems, please do not hesitate to reopen. And thanks again for the teamviewer session -- I should have been able to understand from your description what was happening, but once I saw it, it clicked.

**Comment by cjpoor** [comment]
ZotPlus Error Report 29May2015 10.30am

Updated BBT to 0.10.25. Set debug preferences. Restarted FF.

(F)
1. Exported test collection with “Export Notes” and “Export Files” only checked.
2. Expected collection to be exported as one .bib file and one .pdf file to test folder.
3. Got what I expected. Note that the export created a new folder (named after the exported test collection) within the test folder.

(G)
1. Added and item to the test collection. Exported with “Keep Updated” ticked.
Noticed that the export automatically adds .bib extension to the export name.
Clicked through to overwrite original .bib file.
2. Expected an update of the previously exported .bib file.
3. This happened OK.

(H)
1. Added new item to collection. Exported with “Keep Updated” ticked.
2. Expected an update of the previously exported .bib file.
3. Did not automatically update .bib file

Closed and reopened preferences. New Export appears.

(I)
1. Again added new item to collection. Exported with “Keep Updated” ticked.
2. Expected an update of the previously exported .bib file.
3. Did not automatically update .bib file

Closed and reopened preferences. No difference to exported .bib file (i.e. still not updated).

Error Report ID: http://is.gd/bFTSOX

**Comment by cjpoor** [comment]
Should this be posted as a new issue? The heading is no longer applicable.

**Comment by retorquere** [comment]
A new issue would be much preferred. At least progress has been made, even
if not everything is fixed yet.
